version: "3"
services:
  database:
    container_name: database
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - booking-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "booking-local"

  booking-backend-app:
    container_name: booking-backend
    build:
      context: .
    env_file:
      - .dockerenv
    depends_on:
      - database
    ports:
      - 3000:3000
    networks:
      - booking-network

networks:
  booking-network:

volumes:
  postgres_data:
